// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
const String SCANNING_STARTED = "SCANNING_STARTED";
const String SCANNING_FINISHED_WITH_NO_DEVICE =
    "SCANNING_FINISHED_WITH_NO_DEVICE";

const String STATE_RECOGNIZING = "DEVICE_RECOGNIZING";
const String STATE_CONNECTING = "DEVICE_CONNECTING";
const String STATE_CONNECTED = "DEVICE_CONNECTED";
const String STATE_DISCONNECTED = "DEVICE_DISCONNECTED";
const String STATE_CONNECTING_FAILED = "DEVICE_CONNECTING_FAILED";

const String DEVICE_GATT_INITIATED = "DEVICE_DATA_INITIATED";
const String DEVICE_GATT_CONNECTING = "DEVICE_DATA_CONNECTING";
const String DEVICE_GATT_CONNECTED = "DEVICE_DATA_CONNECTED";
const String DEVICE_GATT_AVAILABLE = "DEVICE_DATA_AVAILABLE";
const String DEVICE_GATT_DISCONNECTED = "DEVICE_DATA_DISCONNECTED";
